apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: property-pvc
  labels:
    app: property-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi